export const GET_ALL_CLAIMS = 'GET_ALL_CLAIMS';
export const GET_ALL_CLAIMS_ERROR = 'GET_ALL_CLAIMS_ERROR';

export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const REMOVE_AUTHENTICATED_USER = 'REMOVE_AUTHENTICATED_USER';

export const SET_APPLICATION_ERROR = 'SET_APPLICATION_ERROR';
